#!/bin/bash

cp ../../src/* .
cp ../data/* .
mv zero* zero_matrix.txt

gfortran -ffree-form -c module_file.F90
make main
num_cores=4
nev=30
echo $nev>input.txt
time OMP_NUM_THREADS=$num_cores ./main  -eps_type arnoldi -st_type sinvert -eps_target 0 -st_ksp_type preonly -st_pc_type lu -st_pc_factor_matrix_solver_type mumps -eps_monitor_conv  -eps_view_vectors -log_view > 'slepc_solution_numcores_'$num_cores'_nev_'$nev'.txt' <input.txt

rm main
rm *.F90 *.o *.mod makefile 
rm real_parts.txt imag_parts.txt weight_matrix.txt zero_matrix.txt input.txt
